<div class="bjui-pageContent">
  <div class="license-cert">
    <table>
      <tbody>
        <tr>
          <th>授权版本</th>
          <td>剧院版</td>
        </tr>
        <tr>
          <th>企业名称</th>
          <td>印象大红袍有限公司</td>
        </tr>
        <tr>
          <th>企业简称</th>
          <td>印象大红袍</td>
        </tr>
        <tr>
          <th>用户人数</th>
          <td>不限</td>
        </tr>
        <tr>
          <th>授权时间</th>
          <td>2015-04-09 至 2016-04-09</td>
        </tr>
        <tr>
          <th>授权域名</th>
          <td>www.yx513.net</td>
        </tr>
        <!--            
            <tr>
                <th></th>
                <td>
                    <span></span>
                </td>
            </tr>
            -->
      </tbody>
    </table>
  </div>
</div>