	<fieldset>
		<legend>按票型划分</legend>
		<table class="table" width="100%">
			<thead>
				<tr>
					<th>票型</th>
					<th>出票数量</th>
					<th>金额</th>
				</tr>
			</thead>
			<tr>
				<td>A票</td>
				<td>3</td>
				<td>864</td>
			</tr>
			<tr>
				<td>B票</td>
				<td>17</td>
				<td>3876</td>
			</tr>
            <tr>
                <td>C票</td>
                <td>20</td>
                <td>6840</td>
            </tr>            			
		</table>
	</fieldset>
	<fieldset>
		<legend>按渠道划分</legend>
		<table class="table" width="100%">
			<thead>
			<tr>
				<th>渠道名称</th>
				<th>出票数量</th>
				<th>金额</th>
			</tr>
			</thead>
			<tr>
				<td>旅行社</td>
				<td>20</td>
				<td>6000</td>
			</tr>
			<tr>
				<td>散客票</td>
				<td>20</td>
				<td>7500</td>
			</tr>			
		</table>
	</fieldset>	